### PR TITLE
Migrate to GitHub Actions and Codecov

### PR DESCRIPTION
**Pull request by un-def**
A demo: https://github.com/un-def/hererocks/commits/master

# Travis CI, AppVeyour → Github Actions

Travis CI no longer provides a free plan for FOSS projects without explicit request:

> Currently, users building on public repositories are required to contact Travis CI support to request free open source credits.

https://blog.travis-ci.com/2021-06-16-ibm-aws

In addition, travis-ci.org is no longer available:

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

# Coveralls → Codecov

Coveralls seems to be broken from time to time. Moveover, it requires some efforts to make it work with Github Actions. At the same time, Codecov "just works".

### CODE REVIEW

**Comment by hishamhm** [comment]
@un-def Thank you!

**Comment by hishamhm** [comment]
@un-def The Windows builds started to fail mysteriously, do you have any idea why? I merged #15 in an attempt to fix them but it made no difference — both builds from [before](https://github.com/luarocks/hererocks/actions/runs/2109065584) and [after](https://github.com/luarocks/hererocks/actions/runs/2109110638) it failed the same way....

**Comment by un-def** [comment]
@hishamhm https://github.com/luarocks/hererocks/pull/15 certainly fixes Windows builds on the latest VS versions, but it had a small incompatibility issue with Python 2.7. I've already fixed it: https://github.com/luarocks/hererocks/pull/19

**Comment by hishamhm** [comment]
@un-def Thank you!! <3

**Pull request merged**
